# Generated by Django 3.0.7 on 2020-06-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('comp_name', models.CharField(help_text='name of Company', max_length=20, primary_key=True, serialize=False)),
                ('comp_passwd', models.CharField(help_text='log in password of Company', max_length=20)),
                ('comp_id', models.CharField(help_text='log in ID of Company', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_name', models.CharField(help_text='name of port', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ship_temp',
            fields=[
                ('ship_name', models.CharField(help_text='name of ship', max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('ship_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
        migrations.CreateModel(
            name='Ship_stored',
            fields=[
                ('ship_name', models.CharField(help_text='name of ship', max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('ship_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('plan_port1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_temp', to='maritime.Port')),
                ('plan_port2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_temp', to='maritime.Port')),
                ('plan_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Ship_stored')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_stored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
                ('plan_port1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_stored', to='maritime.Port')),
                ('plan_port2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_stored', to='maritime.Port')),
                ('plan_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Ship_stored')),
            ],
        ),
        migrations.CreateModel(
            name='Mate_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_name', models.CharField(help_text='name of mate', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('mate_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
        migrations.CreateModel(
            name='Mate_stored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_name', models.CharField(help_text='name of mate', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('mate_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
        migrations.CreateModel(
            name='Eng_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(help_text='name of Engineer', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('eng_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
        migrations.CreateModel(
            name='Eng_stored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(help_text='name of Engineer', max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('eng_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp')),
            ],
        ),
    ]
