# Generated by Django 3.0.7 on 2020-06-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_stored',
            name='plan_comp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan_temp',
            name='plan_comp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='maritime.Comp'),
            preserve_default=False,
        ),
    ]
