# Generated by Django 3.0.7 on 2020-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maritime', '0003_eng_rejected_mate_rejected_plan_rejected_ship_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('gov_id', models.CharField(help_text='log in ID of Government', max_length=20, primary_key=True, serialize=False)),
                ('gov_passwd', models.CharField(help_text='log in password of Government', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modify_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
            ],
        ),
    ]
